### ISSUE TITLE
When using --selector 'user:*' github handles are truncated to 7 characters

### ISSUE THREAD

**Issue by matentzn** [gouttegd/grainyhead#15]
When using --selector 'user:*' github handles are truncated to 7 characters, which means that I need to do some detective work to figure out who is who.. During a future iteration, it would be good if that limit was removed

**Comment by gouttegd** [comment]
I thought you were mostly using JSON output? Truncation is only done in the default “tabular” output.

**Comment by matentzn** [comment]
Turns out I mostly use the markdown output now! But thanks good to know I can get the stats with json. Will try tomorrow.

**Comment by matentzn** [comment]
FYI, the truncation makes sense if you are looking for nicely formatted tables, but especially for markdown use cases this is not so ideal - basically I know have to translate to JSON, and then to markdown, in order to get what I need! The main argument: most usersnames are not much worse than 7 chars anyways, and the utility for markdown reports having the handle clickable is immense! (also right now, its possible a truncated handle in a markdown table points to a different GitHUb user than the one that actually did the contribution).

**Comment by gouttegd** [comment]
The default output format was not initially intended to be usable Markdown, it’s merely a coincidence that it is. It was intended for display in a terminal, hence the fixed-width columns. Agree that fixed-width columns are not needed for Markdown output.
