### ISSUE TITLE
--selector "user:*" cannot handle usernames with strange symbols

### ISSUE THREAD

**Issue by matentzn** [gouttegd/grainyhead#18]
If I run:

```
grainyhead -s mondo metrics --from=2021-01-01 --to=2023-08-09 --selector "user:*"
```

I get:

```
Invalid selector: user:dependabot[bot]
```

Presumably the `[` gives some trouble.

**Comment by gouttegd** [comment]
> Presumably the [ gives some trouble.

Yep. I already had to make a special rule (8b3f745) to exclude `github-actions[bot]`.

I suspected that sooner or later I would run into other similar names that would cause the same problem. Might generalise the special rule to exclude any user with a login name that is not purely alpha-numeric…

**Comment by matentzn** [comment]
Yeah I just tried hacked the code to make it work, and it worked fine, I ts really just the dependabot.

**Comment by gouttegd** [comment]
Thanks for testing. I’ll still exclude all `[bot]`, so that we won’t run into the problem again next time someone starts a new bot.

I don’t think there is any interest in getting individual stats for bot users anyway.

**Comment by matentzn** [comment]
Totally fine by me! thank you!
