### ISSUE TITLE
grh metrics: cache results

### ISSUE THREAD

**Issue by matentzn** [gouttegd/grainyhead#5]
Would it be possible to add a --cache flag to `grh metrics` that dumps (pickels) the gh API queries and then simply allows for change date ranges? I would want to run the command multiple times, and its unnecessary to wait each time for querying the entire git history I would think :)

**Comment by gouttegd** [comment]
Yes, that’s the next thing I was planning to do. :)

**Comment by matentzn** [comment]
Awesome.

**Comment by matentzn** [comment]
Works!

**Comment by gouttegd** [comment]
Closing now. Finer cache control will be for another ticket.
