### ISSUE TITLE
Feature request: break down stats by user

### ISSUE THREAD

**Issue by matentzn** [gouttegd/grainyhead#9]
Depends on #8 

To build our dashboard, we need, on top of the overall aggregate, the output aggregated by user. 

| Event                | Total | User | 
| -------------------- | ----- | -------- |
| Issues opened        |   707 |      @matentzn | 
| Issues closed        |   811 |      @matentzn | 
| Pull requests opened |  1023 |      @matentzn | 
| Pull requests closed |   977 |      @matentzn | 
| Pull requests merged |   897 |      @matentzn | 
| Comments             |  2340 |     @matentzn | 
| Commits              |  3208 |     @matentzn |
| Issues opened        |   707 |      @gouttegd  | 
| Issues closed        |   811 |      @gouttegd | 
| Pull requests opened |  1023 |      @gouttegd | 
| Pull requests closed |   977 |      @gouttegd | 
| Pull requests merged |   897 |      @gouttegd | 
| Comments             |  2340 |     @gouttegd | 
| Commits              |  3208 |     @gouttegd |

This is needed in particular for the JSON.

**Comment by gouttegd** [comment]
Done with 7b44ff1 in JSON mode. Not done yet for Markdown output, but I am not sure this is really useful in that mode.

**Comment by matentzn** [comment]
_a.m.a.z.i.n.g_ can be closed
